### ISSUE TITLE
Launch the first proposition on enter

### ISSUE THREAD

**Issue by Bo-Duke** [Schlipak/nozzle#8]
When searching for an application for example, it would be easier if we could just press enter to launch the first proposition

**Comment by Schlipak** [comment]
To investigate:

- Set entryList focusPolicy to noFocus
- Style ::item:selected:!active to appear active
- Use the event filter to simulate up/down in the entryList
- Event filter on enter --> run selected entry

That way the input never loses focus, which allows to select entries and keep typing without having to focus back on the input

**Comment by Schlipak** [comment]
Done in d93d557a 🎉
